### ISSUE TITLE
custom callables converters

### ISSUE THREAD

**Issue by staabm** [Smile-SA/gdpr-dump#107]
**Is your feature request related to a problem? Please describe.**
we are happily using the faker provided data to anonymize our data.
the currently existing faker-converter supports all faker methods which are supported on the [`Generator` class](https://github.com/FakerPHP/Faker/blob/2114cc6a05b6e371368adfd4261378d7b0f87d84/src/Generator.php#L556).

we tried

```
  mytable:
    converters:
        mycol:
            converter: 'faker' 
            parameters:
                formatter: 'bank' 
```

but this didn't work

> Unknown format "bank"

The fakers Generator class supports only a subset of Faker's actual functionality though.
e.g. there are [static methods on some Provider classes](https://github.com/FakerPHP/Faker/blob/2114cc6a05b6e371368adfd4261378d7b0f87d84/src/Provider/de_DE/Payment.php#L56) which are not callable via the Generator proxy class.

it would be great if we could make use of all available fake data in the Faker library

**Describe the solution you'd like**
I think one common solution to the problem would be a converter type, which allows to call any PHP callable.
this could e.g. look like

```
  mytable:
    converters:
        mycol:
            converter: 'callable' 
            parameters:
                name: '\Faker\Provider\de_DE\Payment::bank'
```

at the same time this formatter could be used to call any php function contained in php-src:

```
  mytable:
    converters:
        mycol:
            converter: 'callable' 
            parameters:
                name: 'str_repeat'
                arguments: ['test', 3]

```

**Describe alternatives you've considered**
-

**Additional context**
-
