### ISSUE TITLE
Add the ability to use fallback value for environment variables

### ISSUE THREAD

**Issue by DnD-Sony** [Smile-SA/gdpr-dump#134]
**Use case**
Sometime the environment variables in .env files could be different between local, staging/production on multiple project in our Web Agency.

**Describe the solution you'd like**
We would like to use the same mechanic provided by Symfony 
[https://symfony.com/doc/current/configuration/env_var_processors.html#built-in-environment-variable-processors](url)
(search the part related for **env(default:fallback_param:BAR)**)

**Describe alternatives you've considered**
We added some modifications to this class `\Smile\GdprDump\Config\Compiler\Processor\EnvVarProcessor` and we would like to submit a Pull Request

The setting now can looks like this

```
database:
  host: '%env(default:DB_HOST:MYSQL_HOST)%'
  user: '%env(default:DB_USER:MYSQL_USER)%'
  password: '%env(default:DB_PASSWORD:MYSQL_PASSWORD)%'
  name: '%env(default:DB_NAME:MYSQL_DB)%'
```
