### ISSUE TITLE
Row specific functions

### ISSUE THREAD

**Issue by swiftotter-davidn** [Smile-SA/gdpr-dump#139]
**Is your feature request related to a problem? Please describe.**
When migrating databases from product to staging or local, I'm looking for a way to unset sensitive values on a per table basis.

**Describe the solution you'd like**
Specifically for Magento 2, the `core_config_data` table often includes sensitive data such as payment API keys or Algolia search credentials. I'm not sure if there is already a way to accomplish this, but I was thinking something like:

```yaml
core_config_data:
  transformations:
    - "UPDATE {{table_name}} SET value = 'dev_local_' WHERE path = 'algoliasearch_credentials/credentials/index_prefix' AND scope_id = 0;"
```

**Describe alternatives you've considered**
Using `app/etc/env.php`, however, that doesn't ensure they've locked the config in their local environment. If a new developer grabs a DB with sensitive data contained in the `core_config_data` table, they could accidentally overwrite production Algolia indexes with the local URL.

**Comment by guvra** [comment]
Hi,

It's already possible with converter conditions:

```yaml
tables:
    core_config_data:
        converters:
            value:
                converter: 'setValue'
                condition: '{{path}} === "algoliasearch_credentials/credentials/index_prefix" && {{scope_id}} === 0"'
                parameters:
                    value: 'dev_local_'
```

You can also change multiple values with the [chain](https://github.com/Smile-SA/gdpr-dump/wiki/Data-Converters#chain) converter.

But I would recommend against doing this. It's better to fix the configuration after you import the dump file (e.g. with an additional SQL file, or a custom Magento command). This allows to update any environment (dev, staging, etc.) with the same dump file.
