### ISSUE TITLE
Skip anonymization for an entity stored in multiple tables

### ISSUE THREAD

**Issue by yutv** [Smile-SA/gdpr-dump#15]
I have a test customer account on the live/preprod website and want to skip it from anonymization. 

In Magento 2, customer data is stored in multiple tables e.g.: 
 - **customer_entity**
 -  **customer_address_entity**
 - etc.

The tool has an ability to add a condition for a table column like:
```
tables:
    customer_entity:
        converters:
            email:
                condition: 'false === strpos({{email}}, "@example.com")'
            firstname:
                condition: 'false === strpos({{email}}, "@example.com")'
            middlename:
                condition: 'false === strpos({{email}}, "@example.com")'
            lastname:
                condition: 'false === strpos({{email}}, "@example.com")'
```

But it has the following disadvantages:

1. You have to duplicate condition to each column to skip entire row 
2. No way to spread this condition on related tables (like **customer_address_entity**) since there is no email column. But both tables are liked by foreign key.

**It would be nice to support a config like:**
```
tables:
    customer_entity:
        skip:
            condition: 'false !== strpos({{email}}, "@example.com")'
            follow_foreign_key: true
```

**Comment by guvra** [comment]
Hi,

It could indeed be interesting to be able to skip anonymization of a row depending on a condition.

It wouldn't entirely solve your problem though:
1. The duplicate information may not be stored in a table that uses foreign keys.
2. Children tables could contain information you must always anonymize.

Another problem is the config format.
The format you proposed is conflicting with the current behavior of the tool. It would interpret the `skip` parameter as a column name.

I'll add this on the todo list :)

**Comment by guvra** [comment]
Added parameter `skip_conversion_if`.

Example:

```yaml
tables:
    users:
        converters:
            email:
                converter: 'randomizeEmail'
            username:
                converter: 'anonymizeText'
        skip_conversion_if: '{{username}} === "admin123"'
```

It is not propagated to children tables (technically not possible without a huge performance loss).
