### ISSUE TITLE
Add a converter which can replace a placeholder with another column

### ISSUE THREAD

**Issue by rawroland** [Smile-SA/gdpr-dump#155]
**Is your feature request related to a problem? Please describe.**
We are currently creating rudimentary dumps in our drupal system by importing the dump in a separate system and replacing user names with a combination of a fixed prefix and the id of the column, e. g. `username_21`. We do something similar with email addresses. Since we have to anonymize more fields, I would like to replace our current solution with this more comprehensive one. However, I have not found a possibility to replace values with other columns using a placeholder.

**Describe the solution you'd like**
I suggest an extension to the `setValue` converter, which would add the possibility to provide a placeholder like `{{some_column}}` and it would replace the placeholder with the real value. An example would look as follows:

```
tables:
    my_table:
        converters:
            my_column:
                converter: 'setValue'
                parameters:
                    value: 'suffix_{{other_column}}'
```

It could then be possible to combine this with other converters like an append or a prepend converter.

**Describe alternatives you've considered**
My current plan is to do the anonymization in two steps, first anonymize with gdpr-dump and then run a command to replace the usernames and emails with the aforementioned process. I would however prefer to do both in one step and I think an extension with placeholders would be a good feature.

**Additional context**
I may also be missing another possibility to implement what I suggested so I am open to suggestions. 

Thanks for your time and effort.

**Comment by guvra** [comment]
Hi,

I think it's already possible to achieve what you want.

Can you try this?
It's a little verbose but I think it should work.

```yaml
users:
    converters:
        username:
            # Generates values like "username_{{ user_id }}"
            converter: 'chain'
            parameters:
                converters:
                    - converter: 'fromContext'
                      parameters:
                          key: 'row_data.user_id'
                    - converter: 'prependText'
                      parameters:
                          value: 'username_'

        email:
            # Generates values like "username_{{ user_id }}@example.org"
            converter: 'chain'
            parameters:
                converters:
                    - converter: 'fromContext'
                      parameters:
                          key: 'row_data.user_id'
                    - converter: 'prependText'
                      parameters:
                          value: 'username_'
                    - converter: 'appendText'
                      parameters:
                          value: '@example.org'
```

The first converter (fromContext) sets the value to the user id, then the next converters add a prefix/suffix.

cf. https://github.com/Smile-SA/gdpr-dump/wiki/Data-Converters#fromcontext
