### ISSUE TITLE
Sales_order and quote not anonymised

### ISSUE THREAD

**Issue by kevin39** [Smile-SA/gdpr-dump#17]
Hi,
On Magento 2.3.2 and using default template without any modification. 
Tables quote and sales_order are not anonymised. I don't understand why, template's settings seems good...

If I set `tables_whitelist `to '`sales_order`', the table is anonymised correctly.
Are you aware of any kind of bug like that ?

My yaml : 
```
---
extends: 'magento2'
version: '2.3.2'

database:
    host: 'localhost'
    user: 'readonly-XXXX'
    password: 'XXX'
    name: 'XXXX'

dump:
    output: 'php://stdout'
    compress: 'none'
    add_drop_table: true
    extended_insert: true
    routines: true

tables_blacklist:
    - 'core_config_data'
    - 'importexport_importdata'
    - 'mst_*'

tables:
    # Address attribute no 285 (address line 1) and 265 (phone)
    customer_address_entity_varchar:
        converters:
            value:
                converter: chain
                parameters:
                    converters:
                        - converter: 'anonymizeText'
                          condition: '{{attribute_id}} == 285'
                        - converter: 'randomizeNumber'
                          condition: '{{attribute_id}} == 265'
```

**Comment by guvra** [comment]
Hi Kevin,

The value of `extends` should be `magento2` instead of `magento2.yaml` (this is a default template).
I guess this is what causes your problem, there is no other issue in your config file.

I just made a test with the same config file (with the fix to the template name), and the tables are anonymized:

```sql
INSERT INTO `quote` VALUES (1,1,'2019-05-29 08:14:19','2019-05-29 08:14:21',NULL,0,0,0,1,1.0000,0,0.0000,0.0000,'EUR','EUR','EUR',36.3900,36.3900,NULL,1,3,1,'f5s2xkugy@example.net',NULL,'V*******',NULL,'C*******',NULL,'1973-11-06 00:00:00',NULL,1,0,NULL,NULL,'000000001',NULL,NULL,'EUR',1.0000,1.0000,NULL,'2',29.0000,29.0000,29.0000,29.0000,1,0,NULL,NULL,0),(2,1,'2019-05-29 08:14:26','2019-05-29 08:14:27',NULL,0,0,0,1,1.0000,0,0.0000,0.0000,'EUR','EUR','EUR',39.6400,39.6400,NULL,1,3,1,'k7r8ff12j@example.net',NULL,'V*******',NULL,'C*******',NULL,'1973-10-17 00:00:00',NULL,1,0,NULL,NULL,'000000002',NULL,NULL,'EUR',1.0000,1.0000,NULL,'2',32.0000,32.0000,32.0000,32.0000,1,0,NULL,NULL,0);
```

**Comment by kevin39** [comment]
Hi,
It's a copy/paste error after many tests. Anyway my "good" config file contains `'magento2'` instead of `magento2 `(without quote). That may be my problem.

I'm trying again. Thanks! I'll be back shortly :)

**Comment by guvra** [comment]
Quotes are not mandatory, it's just a good practice I always follow (without quotes, the config value parsed in php may be a string or a number depending on the value...).

**Comment by kevin39** [comment]
Ok so I don't understand my problem.
My quote table is still not anonymised. How can I debug ?

**Comment by guvra** [comment]
If you use the phar file, you'll need to clone the repository and add break point or var_dump statements in the code.

You could first look here:

- Data conversion: https://github.com/Smile-SA/gdpr-dump/blob/master/src/Dumper/Mysqldump/DataConverterExtension.php#L85
- Dumped tables: https://github.com/Smile-SA/gdpr-dump/blob/master/src/Dumper/SqlDumper.php#L111

**Comment by guvra** [comment]
FYI i tried to reproduce the bug with the following config file:

```yaml
---
extends: 'magento2'
version: '2.3.2'

database:
    name: 'xxx'
    user: 'xxx'
    password: 'xxx'

dump:
    output: 'php://stdout'
    compress: 'none'
    add_drop_table: true
    extended_insert: true
    routines: true

tables_blacklist:
    - 'core_config_data'
    - 'importexport_importdata'
    - 'mst_*'

tables:
    # Address attribute no 285 (address line 1) and 265 (phone)
    customer_address_entity_varchar:
        converters:
            value:
                converter: 'chain'
                parameters:
                    converters:
                        - converter: 'anonymizeText'
                          condition: '{{attribute_id}} == 285'
                        - converter: 'randomizeNumber'
                          condition: '{{attribute_id}} == 265'
```

But the tables are properly anonymized with this config (including quote and sales_order).

**Comment by kevin39** [comment]
Ok. Thank you for your help, I'm debugging using your tips, I hope I'll found my issue.

**Comment by kevin39** [comment]
I found the issue, sorry I pasted above the wrong yaml when I created this issue.
It's related to `skip_conversion_if` (used on another table).

**Everything if working fine** using the following settings :
```---
extends: magento2
version: '2.3.2'

database:
    (hidden)

dump:
    output: 'php://stdout'
    compress: 'none'
    add_drop_table: true
    extended_insert: true
    routines: true

tables_blacklist:
    - 'core_config_data'
    - 'importexport_importdata'
    - 'mst_*'
```

Example : 
```
$ rm -f /mnt/tmpfs/* && ./gdpr-dump test.yaml >> /mnt/tmpfs/test.sql
$ grep "(hidden dummy company name)" /mnt/tmpfs/test.sql |wc -l
1
```
As you can see, there is 1 row returned.

----

Now, using the following settings there are at least **quote** and **sales_order** tables **not anonymised** using following settings : 
```
---
extends: magento2
version: '2.3.2'

database:
    (hidden)

dump:
    output: 'php://stdout'
    compress: 'none'
    add_drop_table: true
    extended_insert: true
    routines: true

tables_blacklist:
    - 'core_config_data'
    - 'importexport_importdata'
    - 'mst_*'

tables:
    admin_user:
        skip_conversion_if: 'strpos({{email}}, "@XXXX") !== false'
```

And the resultat : 
```$ grep wisuel /mnt/tmpfs/test.sql |wc -l
6```

Six row returned...
