### ISSUE TITLE
Feature Request: on truncate set null instead of removing the row

### ISSUE THREAD

**Issue by amenk** [Smile-SA/gdpr-dump#60]
We have the following config for shopware6:

``` 
database:
    host: '%env(DATABASE_HOST)%'
    port: '%env(DATABASE_PORT)%'
    user: '%env(DATABASE_USER)%'
    password: '%env(DATABASE_PASSWORD)%'
    name: '%env(DATABASE_NAME)%'

dump:
    hex_blob: true
    skip_definer: true

tables:
    acl_user_role:
        truncate: true
    cart:
        truncate: true
    customer:
        truncate: true
    customer_address:
        truncate: true
    customer_recovery:
        truncate: true
    dead_recovery:
        truncate: true
    enqueue:
        truncate: true
    google_shopping_account:
        truncate: true
    google_shopping_merchant_account:
        truncate: true
    integration:
        truncate: true
    log_entry:
        truncate: true
    message_queue_stats:
        truncate: true

    newsletter_recipient:
        truncate: true
    order:
        truncate: true
    order_address:
        truncate: true
    order_customer:
        truncate: true
    product_review:
        truncate: true
    refresh_token:
        truncate: true
    scheduled_task:
        truncate: true
    user:
        truncate: true
    user_recovery:
        truncate: true
    version:
        truncate: true
    version_commit:
        truncate: true
    version_commit_data:
        truncate: true
```

The media table referes to the user table in the column. We want to have the media entries (even if the user_id was set in the production database). But the truncate option for `user` causes all the `media` rows to be deleted.

We tried to work around this by first

``` 
    media:
        converters:
            user_id:
                converter: 'setNull'
```

But this does not help - `media` rows get still removed.

is there such a thing like setNull on truncate similar to MySQL's cascade set null?

**Comment by guvra** [comment]
Hi,

I won't be available in the following weeks.
But I think the best solution would be to apply the row deletion only for foreign keys that are defined to delete on cascade.

**Comment by amenk** [comment]
I looked at the code and it seems not trivial to add that. If you'd like to implement this we are happy. Otherwise we probably need some pointers how to structure this, which is also fine after some weeks.

Have a nice break :-)

**Comment by guvra** [comment]
@amenk Well since I won't be available for a few weeks, I made a quick PR that implements what I proposed:
https://github.com/Smile-SA/gdpr-dump/pull/61

It seems to be working, but I didn't have time to do a lot of testing.

**Comment by amenk** [comment]
Wow, thanks, I will test.

This is what I found so far:

1. The reference column is not really set to null, it's just kept. Shall we simulate the SET NULL action by also exporting a null for the `user_id` column or not?
2. The foreign key scanning is super slow (around 1-2 seconds per table, the Shopware database takes around 4 minutes to analyze), because information_schema queries are not optimized -> I can have a look at this
3. In the end I got a duplicate-column error, I cannot reproduce this with a database that only has the users + media table, so I best look first at 2. :-)

**Comment by amenk** [comment]
3. seems to be fixed by https://github.com/iMi-digital/gdpr-dump/commit/3f3fa9cdc2262b936318f827f342a0db848f6a57

**Comment by amenk** [comment]
2. fixed by https://github.com/iMi-digital/gdpr-dump/commit/33eeebc7a906ac8905bf028a062501bf9ef28db1

1. can be fixed manually by the workaround mentioned initially
The question is whether we want to solve 1. or not. It would be cool, but could become very complex, especially if table limits are used. We always would need to check if the referenced entry is there or not.
What do you think?

**Comment by guvra** [comment]
@amenk 

1. It's not possible to apply SET NULL foreign keys when creating the dump. Well, it's theorically possible, but the performance would be terrible. It's only possible to apply CASCADE foreign keys, thanks to a clever trick (applying filters in the SELECT query that fetches the data to dump.

2. Your PR did not pass the unit tests, I closed it and implemented the optimization on the master branch.

3. I'm not following you, what workaround are you talking about?

**Comment by amenk** [comment]
alright,
I forgot what I meant exactly with the "workaround" ;-)

I think it is all fine then.

**Comment by guvra** [comment]
I'm still debating whether to merge the PR though.

If we only apply the cascade deletion for foreign keys that use the "cascade" mode, the database might end up in a corrupted state.

For example :

- table "stores"
- table "customers" with store_id foreign key that references the store table (no action mode)

If we apply a filter on the stores table, it won't be repercuted on the customers table (because the FK is not configured to use the cascade mode).

Then the dump will end up with customer entries that reference stores that do not exist.
Which violates the foreign key, so the database is corrupted.

**Comment by guvra** [comment]
Maybe something like this?

To disable the feature:

```yaml
filter_propagation:
    enabled: false
```

To leave it enabled but ignore a specific foreign key:

```yaml
filter_propagation:
    ignored_foreign_keys: [
        {"table": "media", "constraint_name": "fk1"}
    ]
```

**Comment by guvra** [comment]
I updated the PR #61 with this new logic.

**Comment by amenk** [comment]
Should we add some info to the docs, that you might want to use `setNull` converters to get more consistent data, if the propagation is on?

**Comment by guvra** [comment]
I think it might be a little too specific, and using the setNull converter might not solve the issue (it cannot detect which data has to be set to null and which must be preserved).

Anyway, PR #61 is merged into master, and included in release 2.3.0 :)

**Comment by amenk** [comment]
Just for future readers and sake of completeness: With the PR #61 our problem can be solved like this. It kind of simulates a `DELETE SET NULL`

```
filter_propagation:
    ignored_foreign_keys:
        - "fk.media.user_id"
```

and

```
tables:    
    media:
        converters:
            user_id:
                converter: 'setNull'
```

Thanks again for the feature :-)
