### ISSUE TITLE
Please provide a YAML configuration example of the usage of database driver_options to enable SSL connection

### ISSUE THREAD

**Issue by tedvanderveen** [Smile-SA/gdpr-dump#65]
For our project we have to connect to a MySQL database environment that requires SSL enabled connections. But I'm wrapping my head around on how to set this up in the config YAML.
Can you please provide an example?

**Comment by tedvanderveen** [comment]
I tried various options, but cannot get it to work. For example:

```
database:
    host: '%env(DB_HOST)%'
    user: '%env(DB_USER)%'
    password: '%env(DB_PASSWORD)%'
    name: '%env(DB_NAME)%'
    driver_options:
        PDO::MYSQL_ATTR_SSL_CA: '%env(MYSQL_ATTR_SSL_CA)%'
```
