### ISSUE TITLE
Configuration library for Magento 2 extensions?

### ISSUE THREAD

**Issue by peterjaap** [Smile-SA/gdpr-dump#87]
Hi! First of all; great job on this tool!

We have created a similar tool like this (https://github.com/elgentos/masquerade) but ours is less versatile and slower. So we have decided to sunset Masquerade and internally we have already moved over to gdpr-dump.

In the wiki of Masquerade, we have some predefined configurations on a vendor/extension basis. Maybe it's a thought to add something like this here too? https://github.com/elgentos/masquerade/wiki

We have already ported some of the configurations we used with Masquerade to gdpr-dump, here is the complete list we're now using:

```
admin_activity:
  converters:
    remote_ip:
      converter: 'faker'
      parameters:
        formatter: 'ipv4'

admin_activity_login_log:
  converters:
    remote_ip:
      converter: 'faker'
      parameters:
        formatter: 'ipv4'

am_customform_answer:
  converters:
    ip:
      converter: 'faker'
      parameters:
        formatter: 'ipv4'

amasty_acart_blacklist:
  converters:
    customer_email:
      converter: 'randomizeEmail'

amasty_acart_history:
  converters:
    email_subject:
      converter: 'randomizeEmail'
    email_body:
      converter: 'randomizeEmail'

amasty_acart_rule_quote:
  converters:
    customer_email:
      converter: 'randomizeEmail'
    customer_firstname:
      converter: 'anonymizeText'
    customer_lastname:
      converter: 'anonymizeText'
    customer_phone:
      converter: 'anonymizeText'

amasty_amrma_request:
  converters:
    email:
      converter: 'randomizeEmail'
    customer_firstname:
      converter: 'anonymizeText'
    customer_lastname:
      converter: 'anonymizeText'
    notes:
      converter: 'anonymizeText'

amasty_blog_comments:
  converters:
    email:
      converter: 'randomizeEmail'

amasty_gdpr_consent_log:
  converters:
    logged_email:
      converter: 'randomizeEmail'

amasty_groupcat_request:
  converters:
    name:
      converter: 'anonymizeText'
    email:
      converter: 'randomizeEmail'
    phone:
      converter: 'anonymizeNumber'
    comment:
      converter: 'anonymizeText'
    message_text:
      converter: 'anonymizeText'

amasty_hideprice_request:
  converters:
    name:
      converter: 'anonymizeText'
    email:
      converter: 'randomizeEmail'
    phone:
      converter: 'anonymizeNumber'
    comment:
      converter: 'anonymizeText'
    message_text:
      converter: 'anonymizeText'

aw_followup_queue:
  converters:
    recipient_email:
      converter: 'randomizeEmail'

aw_pq_email_queue:
  converters:
    recipient_email:
      converter: 'randomizeEmail'

aw_pq_notification_subscriber:
  converters:
    customer_email:
      converter: 'randomizeEmail'

aw_pq_question:
  converters:
    author_email:
      converter: 'randomizeEmail'
  
  mageplaza_blog_comment:
    converters:
      user_email:
        converter: 'randomizeEmail'

bss_product_alert_stock:
  converters:
    customer_email:
      converter: 'randomizeEmail'

catgento_activity:
  converters:
    remote_ip:
      converter: 'faker'
      parameters:
        formatter: 'ipv4'

catgento_login_activity:
  converters:
    remote_ip:
      converter: 'faker'
      parameters:
        formatter: 'ipv4'

infomodus_caship:
  converters:
    company_type:
      converter: 'anonymizeText'
    country_ids:
      converter: 'anonymizeText'

kiwicommerce_activity:
  converters:
    remote_ip:
      converter: 'faker'
      parameters:
        formatter: 'ipv4'

kiwicommerce_customer_password_log:
  converters:
    customer_email:
      converter: 'randomizeEmail'

kiwicommerce_email_log:
  converters:
    sender_email:
      converter: 'randomizeEmail'
    recipient_email:
      converter: 'randomizeEmail'
    email_subject:
      converter: 'anonymizeText'

kiwicommerce_login_activity:
  converters:
    remote_ip:
      converter: 'faker'
      parameters:
        formatter: 'ipv4'

kiwicommerce_login_as_customer:
  converters:
    customer_email:
      converter: 'randomizeEmail'
      unique: true
    admin_username:
      converter: 'anonymizeText'
    admin_name:
      converter: 'anonymizeText'
    ip:
      converter: 'faker'
      parameters:
        formatter: 'ipv4'

mageplaza_company_accounts_company:
  converters:
    city:
      converter: 'anonymizeText'
    country_id:
      converter: 'anonymizeText'
    email:
      converter: 'randomizeEmail'
    erp_company_id:
      converter: 'anonymizeText'
    street:
      converter: 'anonymizeText'
    telephone:
      converter: 'randomizeNumber'

mageplaza_smtp_log:
  converters:
    email_content:
      converter: 'randomizeEmail'

mega_productinquery_query_log:
  converters:
    customer_email:
      converter: 'randomizeEmail'

vat_validation:
  converters:
    vat_trader_address:
      converter: 'anonymizeText'
```
