### ISSUE TITLE
How to set environment variables?

### ISSUE THREAD

**Issue by Luke1982** [Smile-SA/gdpr-dump#88]
I've tried creating a `.env` and setting OS environment variables, but both were not picked up. What's the recommended way to do this?

**Comment by guvra** [comment]
There's no recommended way to achieve this, it entirely depend on how you create the dump (from the command-line, from a CI pipeline...). This is up to you to determine what's best depending on the context.

**Comment by Heiko-H** [comment]
I have the same issue. I always get an error message when i try to use the .env file and vars. 

The files in the dir: 
- .env
- config.yaml
- gdpr-dump.phar (Ver. 3.1.1 on php 8.0)

The content of file **.env**: 
```
DB_HOST=localhost
DB_USER=test
DB_PASSWORD=test
DB_NAME=test
```

The content of file **config.yaml**: 
```
database:
    host: '%env(DB_HOST)%'
    user: '%env(DB_USER)%'
    password: '%env(DB_PASSWORD)%'
    name: '%env(DB_NAME)%'
```

I execute the command like this: 
```
php gdpr-dump.phar config.yaml > dump.sql 
```

And i get the following error message: `The environment variable "DB_HOST" is not defined.`

I can't figure out, what i have done wrong.

**Comment by staabm** [comment]
afaik gdpr-dump does not load a `.env` file. you have todo it on youown

**Comment by guvra** [comment]
Is there any point to using an env file anyway?
Unless i'm missing something, it's the exact equivalent of doing this (which is already possible):

```
./gdpr-dump.phar /path/to/mydb.yaml /path/to/env.yaml
```

Where env.yaml would be a standalone file that contains the database credentials, e.g.:

```yaml
database:
    host: 'mydb'
    user: 'myuser'
    # ...
```
