### ISSUE TITLE
empty string in db columns

### ISSUE THREAD

**Issue by staabm** [Smile-SA/gdpr-dump#94]
### Preconditions

GdprDump Version: 4.0.3

PHP Version: PHP 8.1.27

Database Version: mysql 8.0.36

### Steps to reproduce

1. create a table with 100.000 empty strings in a varchar column
2. run `gdpr-dump.phar config.yaml` with the following config

```
tables:
  myTable:
    converters:
      myColumn:
        converter: 'randomizeEmail'
        condition: '{{myColumn}} !== null'
        unique: true
        parameters:
            domains: ['example.org']
```

### Expected result
1. email addresses are properly randomized

### Actual result
error: `Maximum retries of 100 reached without finding a unique value.`

**Comment by guvra** [comment]
Hi,

It seems normal to me.
Empty strings are left as-is because there is no character to randomize.
GdprDump tries to find a unique value (because of `unique: true`), but it is never able to do so, because the value returned by the converter is always an empty string.

Could you try with this configuration?

```yaml
tables:
    myTable:
        converters:
            myColumn:
                converter: 'randomizeEmail'
                condition: '{{myColumn}} !== ""'
                unique: true
                parameters:
                    domains: ['example.org']
```
