### ISSUE TITLE
Missing possibility to use filters as or

### ISSUE THREAD

**Issue by tobihille** [Smile-SA/gdpr-dump#96]
Hello, first let me thank you for the awesome software ❤️

Not sure if it's a bug report but as I have an SQL error due to the usage I would classify it as this 😅

I use the current version (4.0.3) to anonymize an OpenMage database.
I want to limit the amount of orders in the dump and currently do this in a copy of the live DB like this:
```bash
#!/bin/bash
cutoff=$(date -d "-7 days" "+%Y-%m-%d")
[... then execute the following query]
delete from sales_flat_order where created_at < '$cutoff' and increment_id not in ('some-number', 'some-other-number');
```

I now wanted to convert this to only execute this in gdpr-dump but I saw that there is always AND used:
https://github.com/Smile-SA/gdpr-dump/blob/55ea19ee91899fe8f70a40d09fdfe41c52575f36/src/Dumper/Mysql/TableFilterExtension.php#L211

As an alternative I tried to use a variable like this (which can not work as I see in issue #89):
```
variables:
    filtered_order_ids: 'SELECT sfo.entity_id FROM sales_flat_order sfo WHERE sfo.increment_id IN('some-numer', 'some-other-numer') OR sfo.created_at > DATE_SUB(now(), INTERVAL 7 DAY)'
...
sales_flat_order:
        filters:
            - ['increment_id', 'in', @filtered_order_ids]
```

### Preconditions

GdprDump Version: 4.0.3

PHP Version: 8.2

Database Version: MariaDB 10.6

### Steps to reproduce

No exact steps, sorry.

### Expected result
1. I expect the filtered orders by date including orders that are older than that but 'recovered' by the other query.

### Actual result
1. When using the filter no orders are contained because the queries contradict each other using `AND`
2. When using the variable I get this errormessage: `SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') AND ((order_id IN (SELECT * FROM (SELECT entity_id FROM sales_flat_ord...' at line 1`

**Comment by tobihille** [comment]
The reason for the difference is, that previously I deleted the data and now in the filter I'm selecting the data that would otherwise remain after the deletion.
Some examples might illustrate this:
I want the orders from the last 7 days, so `updated_at` needs to be `greater than` `2024-02-01` and additionally I want orders with the `increment_id` `in` `'123456', '123457', '123458', '123459'` to remain in the dump.

**Comment by guvra** [comment]
>  I want the orders from the last 7 days, so updated_at needs to be greater than 2024-02-01 and additionally I want orders with the increment_id in '123456', '123457', '123458', '123459' to remain in the dump.

OK so recently updated OR in a list of hardcoded ids.

That's indeed not currently supported :(

It would require to implement nested filters, for example:

```yaml
tables:
    sales_order:
        filters:
            -
                - ['updated_at', 'gt', 'expr: date_sub(now(), interval 7 day)']
                - ['increment_id', 'notIn', ['xxx', 'yyy']]
```

**Comment by guvra** [comment]
@tobihille Actually I think it's possible, could you try with the following config:

```yaml
tables:
    sales_order:
        filters:
            - ['entity_id', 'in', 'expr: select entity_id from sales_order where updated_at > date_sub(now(), interval 7 day) or increment_id not in ("123456", "123457', "123458", "123459")'
```

**Comment by tobihille** [comment]
Thanks for the suggestion, looks promising. Sadly I got the folIowing error:
```
The following errors were detected:
  - [tables.sales_flat_quote.filters[1]] There must be a minimum of 2 items in the array
```

Also I'm currently trying to figure out a way to implement it via De Morgan: https://en.wikipedia.org/wiki/De_Morgan%27s_laws
The SQL that would need to be executed would be: 
```SQL
SELECT *
FROM sales_flat_order
WHERE NOT (increment_id NOT IN ("123456", "123457", "123458", "123459") 
AND 
created_at <= DATE_SUB(NOW(), INTERVAL 7 DAY))
```
But I'm currently scratching my head how to add it as a filter, I probably can't give you an update today 😅

**Comment by guvra** [comment]
> Thanks for the suggestion, looks promising. Sadly I got the folIowing error:

I forgot to add the closing bracket of the array, I edited the example, could oyu retry?

**Comment by tobihille** [comment]
I already had the closing bracket set, no worries :-)
Without the bracket it reports this:
```
Unable to parse the YAML input.
```

**Comment by guvra** [comment]
I also forgot to fix a missing quote

Hopefully this will work now:

```yaml
tables:
    sales_order:
        filters:
            - ['entity_id', 'in', 'expr: select entity_id from sales_order where updated_at > date_sub(now(), interval 7 day) or increment_id not in ("123456", "123457", "123458", "123459")']
```

**Comment by tobihille** [comment]
> I also forgot to fix a missing quote

No worries. I need to replace the IDs with my own, I don't want to publish order numbers on the internet 😅

**Comment by tobihille** [comment]
Maybe I'm just blind at the moment and I made a typo. I will check tomorrow with a fresh perspective 😉 
In any case: thank you for the huge help - and of course for the tool as it is ❤️

**Comment by tobihille** [comment]
Yeah, I was blind, I had an unfinished statment inside of my config file that was triggering the issue.
Generally it worked. Sadly I got this error:
```
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') AND ((`order_id` IN (SELECT * FROM (SELECT `entity_id` FROM `sales_flat_ord...' at line 1
```
I would love if I can extend the error output to give you more details, sorry.

The full config for the table is this (maybe something is interfering):
```
    sales_flat_order:
        filters:
          - ['entity_id', 'in', 'expr: SELECT sfo.entity_id FROM sales_flat_order AS sfo WHERE sfo.updated_at > DATE_SUB(NOW(), INTERVAL 7 DAY) OR sfo.increment_id in ("12345", "12346", "12347")']
        converters:
            customer_email:
                converter: 'randomizeEmail'
                parameters:
                    domains: ['<my.domain>']
            customer_prefix:
                converter: 'anonymizeText'
            customer_firstname:
                converter: 'anonymizeText'
            customer_middlename:
                converter: 'anonymizeText'
            customer_lastname:
                converter: 'anonymizeText'
            customer_suffix:
                converter: 'anonymizeText'
            customer_dob:
                converter: 'anonymizeDateTime'
            customer_note:
                converter: 'anonymizeText'
            remote_ip:
                converter: 'anonymizeText'
            x_forwarded_for:
                converter: 'anonymizeText'
            coupon_rule_name:
                converter: 'anonymizeText'
```
I would love to do an PR in the future, just need to find some private time, so no promises there 😅
